### ISSUE TITLE
Create a shopify app for integration with cliniko

### ISSUE THREAD

**Issue by dominikwilkowski** [the-working-party/learning#22]
https://github.com/redguava/cliniko-api

**Comment by oksushi** [comment]
Cliniko is the most advanced and affordable healthcare practice management system. Cliniko is completely web-based, secure and reliable and has no upfront costs or contracts.

**Comment by oksushi** [comment]
@dominikwilkowski What would the integration look like? Is it for purchasing appointments?

**Comment by dominikwilkowski** [comment]
Yes for appointments, displaying time slots, blocking dates for certain products availability.... etc?!

**Comment by oksushi** [comment]
Isn’t this what Cliniko does?

**Comment by dominikwilkowski** [comment]
yes... it does not however integrate with shopify...

**Comment by oksushi** [comment]
I get that :)

Just wondering what Shopify would be doing in the “integration”

**Comment by dominikwilkowski** [comment]
I'd think the above stated?

**Comment by oksushi** [comment]
Not with any clarity!

**Comment by dominikwilkowski** [comment]
> Sydneyremedialmassage.com.au is who I work with now, they use cliniko and everyone is commenting how easy it is to book. Something similar in the booking system is good

**Comment by dominikwilkowski** [comment]
This is what the integration looks like now:

http://www.garrylukemassage.com.au/book.html
http://www.nigglesandknotsmassage.com.au/book-massage-online/
https://movetrainperform.cliniko.com/bookings#location
http://www.ateasechiropractic.com.au/#!bookings-and-forms/cfvg

Either iframes, off site or very limited design to make it look like it is on your page.
No real integration which could be on the site and look much more native...

A whole range of Health Professionals using Cliniko system at the moment. Above I've put in massage therapists, Exercise Physiologists, Chiropractors and I think one has yoga as well. ... I think there is potential.

**Comment by oksushi** [comment]
Alright — I can see the way it’s currently working. 

So instead, we would have an appointment “product” for each therapist. The customer can view the available times & dates on the product page, where they are selected as _line item properties_ in Shopify. The information is pulled in dynamically from the Cliniko API.

On booking and payment, Shopify tells Cliniko the date and time, so Cliniko makes the booking and informs the customer.

Something like that?

**Comment by dominikwilkowski** [comment]
:+1:

**Comment by oksushi** [comment]
Any additional thoughts on this? Is your friend proceeding with it?

**Comment by dominikwilkowski** [comment]
he's on holiday currently but wants to get this running... not a coder though ;)

**Comment by oksushi** [comment]
Any word from your friend?

**Comment by dominikwilkowski** [comment]
He got back a week ago. I'll have a catchup with him this week

**Comment by oksushi** [comment]
:+1:

**Comment by oksushi** [comment]
Any word from your friend?

**Comment by dominikwilkowski** [comment]
He called me three times in the last three days... I always missed them. Just send him a message...

**Comment by dominikwilkowski** [comment]
so had a catch up with the dude yesterday. He now want's to move away from cliniko as they just increased their prices :)
I will investigate what app you might use for selling appointments ...

closing this for now
