### ISSUE TITLE
build a node calDAV app to sync milestones and whatnot to your calendar

### ISSUE THREAD

**Issue by dominikwilkowski** [the-working-party/learning#24]
I had a look.

For GitHub integration I would use:
https://github.com/pksunkara/octonode

Now the iCal integration is a bit more tricky but covered pretty well here:
https://github.com/cozy/cozy-ical
and
https://github.com/tritech/node-icalendar
and
https://github.com/sebbo2002/ical-generator

Last but not least the calDAV server:
https://github.com/LordEidi/fennel
https://github.com/FND/jsDAV

The server seems to be the hardest...

**Comment by oksushi** [comment]
Might not need to sync to an actual calendar — unless leveraging something like Google Calendar could work?

**Comment by oksushi** [comment]
I think this isn’t required anymore due to ZenHub updates :)
