### ISSUE TITLE
Standardize labels across all repos

### ISSUE THREAD

**Issue by ed-codes** [the-working-party/learning#4]
I keep having to create the same labels/colors for different repos e.g. - Performance(blue), Design(purple) etc...

Explained here
http://mstrick.com/github-feature-request-copy-repository-issue-labels/

Possible Solution
https://wpxtre.me/blog/tips/standardize-issue-labels-between-your-github-repos/#.VEdZFovLdm0

**Comment by oksushi** [comment]
Not sure I like this approach.

Perhaps we just need to discuss and agree on a set of labels to use, and then I set those labels up when creating a project?

**Comment by oksushi** [comment]
- UX/Design
- CSS
- JavaScript
- Code
- Anything else?

**Comment by ed-codes** [comment]
- Performance/Optimization
- Content
- Browser Testing

**Comment by oksushi** [comment]
![screenshot 2014-11-24 12 39 42](https://cloud.githubusercontent.com/assets/466722/5160162/3606c7b6-73d7-11e4-9980-4cfe9b82a55e.png)
